project_name: gh

builds:
  - <<: &build_defaults
      binary: bin/actions-sync
    id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]
  - <<: *build_defaults
    id: windows
    goos: [windows]
    goarch: [amd64]
